'use strict';
window.Model = (() => {
 const pages = [
 ['شروع مدیریتی','نقشه راه استقرار نظام مدیریت کارخانه','از راه‌اندازی فیزیکی تا سازمانی که قابلیت رشد دارد'],
 ['آینده کارخانه','این کارخانه قرار است به چه سازمانی تبدیل شود؟','تصویر آینده را به تصمیم‌های امروز پیوند بزنید.'],
 ['نقشه استراتژی','از نتیجه مالی تا محرک عملیاتی','نتایج مالی، پیامد عملکرد فرآیندهای عملیاتی‌اند.'],
 ['معماری فرآیند','یک کارخانه؛ جریان‌های به‌هم‌پیوسته','فرآیندهای انتها به انتها را ببینید و فرآیندهای حیاتی را مشخص کنید.'],
 ['نگاه بین‌واحدی','مسئله مشترک، مسئولیت مشترک','هر شاخص از مرز چند واحد سازمانی عبور می‌کند.'],
 ['کاکپیت مدیریت','یک کارخانه؛ یک نسخه از حقیقت','نمونه مرور عملکرد برای گفت‌وگو و تصمیم‌گیری مدیریتی'],
 ['درخت محرک شاخص','هدف را به محرک‌های قابل مدیریت تبدیل کنید','یک شاخص را انتخاب کنید و مسیر اثرگذاری را بررسی کنید.'],
 ['نظام جلسات','از مشاهده انحراف تا پیگیری تصمیم','داشبورد بدون نظام تصمیم‌گیری، فقط نمایش اطلاعات است.'],
 ['تحلیل مسئله','از مسئله پراکنده تا مسیر اقدام','فرضیه‌های تحلیل را با مدیران بررسی و به تصمیم تبدیل کنید.'],
 ['نقشه راه اجرا','مسیر استقرار نظام مدیریت','ترتیب وابستگی‌ها، پیش از تعیین مدت و هزینه پروژه'],
 ['ثبت جلسه','گفت‌وگو را به توافق قابل پیگیری تبدیل کنید','اولویت، مسئله، تصمیم یا سؤال را سریع ثبت کنید.'],
 ['جمع‌بندی مدیریتی','Management Start-up Blueprint','تصویر اولیه نظام مدیریتی موردنیاز برای راه‌اندازی و رشد کارخانه']
 ];
 const chain=[['استراتژی',2],['مدل عملیاتی',1],['قابلیت','cap'],['فرآیند',3],['سازمان و مالکیت',3],['شاخص و کنترل',6],['داده و سیستم','data'],['نظام مدیریت',7],['بهبود مستمر',9]];
 const axes=['بازار','محصولات','ظرفیت','فروش','حاشیه سود','منابع انسانی','فناوری','کیفیت','صادرات','اتوماسیون','توسعه خطوط','کانال‌های فروش'];
 const prompts={
 'بازار':['بخش مشتری هدف چیست؟','چه مزیت رقابتی باید ایجاد شود؟','اطلاعات بازار از کجا تأمین می‌شود؟'],
 'محصولات':['سبد محصول چه تغییری می‌کند؟','توسعه محصول چه مالک و دروازه تأییدی دارد؟','پیچیدگی BOM و تغییرات محصول چگونه کنترل می‌شود؟'],
 'ظرفیت':['گلوگاه ظرفیت کجاست؟','شیفت، تعمیرات و تأمین مواد چگونه هماهنگ می‌شوند؟'],
 'فروش':['پیش‌بینی تقاضا چطور ساخته می‌شود؟','فروش با ظرفیت و نقدینگی چگونه هم‌راستا می‌شود؟'],
 'حاشیه سود':['محرک‌های قیمت و هزینه کدام‌اند؟','داده بهای تمام‌شده قابل اتکاست؟'],
 'منابع انسانی':['کدام شایستگی‌های کلیدی باید ایجاد شود؟','مالکیت فرآیندها و جانشین‌پروری چگونه تعریف می‌شوند؟'],
 'فناوری':['مالک داده‌های پایه کیست؟','ERP و BI چه تصمیم‌هایی را پشتیبانی می‌کنند؟'],
 'کیفیت':['استاندارد و حدود پذیرش محصول چیست؟','کنترل فرآیند، ردیابی و CAPA چگونه به هم متصل می‌شوند؟'],
 'صادرات':['ردیابی محصول (Traceability)','انطباق مقرراتی بازار مقصد (Regulatory Compliance)','استانداردهای کیفیت (Quality Standards)','صلاحیت تأمین‌کنندگان (Supplier Qualification)','الزامات بسته‌بندی (Packaging Requirements)','قابلیت زنجیره تأمین (Supply Chain Capability)'],
 'اتوماسیون':['کنترل پارامترهای فرآیند چه داده‌ای نیاز دارد؟','نگهداری تجهیزات و مهارت اپراتورها چه تغییری می‌کند؟'],
 'توسعه خطوط':['مدیریت پروژه و انتقال به بهره‌برداری چگونه است؟','ظرفیت انبار و تأسیسات کافی خواهد بود؟'],
 'کانال‌های فروش':['سیاست سطح خدمت هر کانال چیست؟','شرایط اعتباری و توزیع چگونه تفکیک می‌شوند؟']
 };
 const capabilities=['برنامه‌ریزی یکپارچه','مدیریت بهای تمام‌شده','ردیابی محصول','مدیریت کیفیت','صلاحیت تأمین‌کنندگان','قابلیت اطمینان تجهیزات','توسعه محصول','مدیریت داده‌های پایه','توسعه شایستگی','مدیریت نقدینگی','مدیریت صادرات','بهبود مستمر'];
 const layers=[
 ['مالی','Financial',['Revenue Growth','Margin','Cash Flow','Working Capital','ROIC']],
 ['مشتری و بازار','Customer & Market',['Market Growth','Customer Satisfaction','OTIF','Product Quality','New Products']],
 ['تعالی عملیاتی','Operational Excellence',['OEE','Yield','Waste','Inventory','Forecast Accuracy','Production Plan Attainment','Quality','Maintenance Reliability']],
 ['سازمان و قابلیت','Organization & Capability',['People','Competency','Leadership','Culture','Data','Technology','Continuous Improvement']]
 ];
 const labels={ 'Revenue Growth':'رشد درآمد',Margin:'حاشیه سود','Cash Flow':'جریان نقد','Working Capital':'سرمایه در گردش',ROIC:'بازده سرمایه','Market Growth':'رشد بازار','Customer Satisfaction':'رضایت مشتری',OTIF:'تحویل کامل و به‌موقع','Product Quality':'کیفیت محصول','New Products':'محصولات جدید',OEE:'اثربخشی کلی تجهیزات',Yield:'بازده مواد',Waste:'ضایعات',Inventory:'موجودی','Forecast Accuracy':'دقت پیش‌بینی','Production Plan Attainment':'تحقق برنامه تولید',Quality:'کیفیت','Maintenance Reliability':'قابلیت اطمینان نگهداری',People:'نیروی انسانی',Competency:'شایستگی',Leadership:'رهبری',Culture:'فرهنگ',Data:'داده',Technology:'فناوری','Continuous Improvement':'بهبود مستمر',EBITDA:'سود عملیاتی پیش از استهلاک','Plan Attainment':'تحقق برنامه تولید',Downtime:'توقف تجهیزات','Inventory Days':'روزهای موجودی','Supplier Performance':'عملکرد تأمین‌کننده','First Pass Yield':'قبولی در بار اول',NCR:'عدم انطباق','CAPA Aging':'عمر اقدامات اصلاحی','Customer Complaints':'شکایات مشتری',Productivity:'بهره‌وری',Turnover:'ترک خدمت',Absenteeism:'غیبت',Training:'آموزش',Revenue:'درآمد','Product Mix':'ترکیب محصول','Procurement Cost':'هزینه خرید',Price:'قیمت فروش',Energy:'انرژی','Labor Productivity':'بهره‌وری نیروی کار',Availability:'دسترس‌پذیری',Performance:'سرعت عملکرد','Safety Stock':'موجودی اطمینان','Batch Size':'اندازه بچ',Forecast:'پیش‌بینی','Production Planning':'برنامه‌ریزی تولید',Procurement:'تدارکات',Sales:'فروش',Finance:'مالی',Production:'تولید','Supply Chain':'زنجیره تأمین',HR:'منابع انسانی',CEO:'مدیرعامل'};
 Object.assign(labels,{
 'Strategic Analysis':'تحلیل استراتژیک',Objectives:'اهداف',Initiatives:'ابتکارات',Review:'بازنگری',Assumptions:'فرضیات',Approval:'تأیید', 'KPI Design':'طراحی شاخص', 'Data Validation':'اعتبارسنجی داده',Action:'اقدام',Identify:'شناسایی',Assess:'ارزیابی',Mitigate:'کاهش ریسک',Monitor:'پایش',Inputs:'ورودی‌ها',Decisions:'تصمیم‌ها','Follow-up':'پیگیری',Opportunity:'فرصت','Business Case':'توجیه کسب‌وکار',Launch:'آغاز اجرا','Market Insight':'شناخت بازار',Segmentation:'بخش‌بندی بازار','Customer Requirements':'نیازمندی‌های مشتری',Validation:'اعتبارسنجی',Consensus:'توافق','Demand Review':'مرور تقاضا','Supply Review':'مرور عرضه',Reconciliation:'هم‌راستاسازی','Executive S&OP':'جلسه مدیریتی فروش و عملیات',Capacity:'ظرفیت',Schedule:'زمان‌بندی',Release:'آزادسازی','Line Preparation':'آماده‌سازی خط','Batch Execution':'اجرای بچ',Consumption:'مصرف','Batch Closure':'بستن پرونده بچ',Quarantine:'قرنطینه',FEFO:'خروج بر مبنای نزدیک‌ترین انقضا','Stock Accuracy':'دقت موجودی',Dispatch:'ارسال',Order:'سفارش',Picking:'برداشت کالا',Routing:'مسیریابی',Delivery:'تحویل','Proof of Delivery':'تأیید تحویل',Service:'خدمت',Complaint:'شکایت',Feedback:'بازخورد',Accounting:'حسابداری',Credit:'اعتبار',Reporting:'گزارش‌دهی','Workforce Planning':'برنامه‌ریزی نیروی انسانی',Recruitment:'جذب','Asset Register':'شناسنامه تجهیزات','Preventive Maintenance':'نگهداری پیشگیرانه','Work Order':'دستور کار',Reliability:'قابلیت اطمینان',Design:'طراحی',Commissioning:'راه‌اندازی','Change Control':'کنترل تغییر','Technical Documentation':'مستندات فنی','Master Data':'داده‌های پایه',Access:'دسترسی',Integration:'یکپارچگی',Backup:'پشتیبان‌گیری',Support:'پشتیبانی',Hazard:'خطر',Controls:'کنترل‌ها',Inspection:'بازرسی',Incident:'رویداد',Facilities:'امکانات',Services:'خدمات',Documents:'اسناد'
 });
 const drivers={
 Margin:['Price','Product Mix','Procurement Cost','Yield','Waste','Labor Productivity','OEE','Energy','Inventory'],
 OEE:['Availability','Performance','Quality'],
 OTIF:['Forecast','S&OP','Production Planning','Material Availability','Production','Warehouse','Distribution'],
 'Inventory Days':['Forecast','Procurement','Production Planning','Batch Size','Sales','Safety Stock'],
 Waste:['Supplier Quality','Process Parameters','Standard Consumption','Actual Consumption','Yield','Training','Maintenance Reliability'],
 'Revenue Growth':['Market Growth','New Products','Customer Satisfaction','OTIF'],
 'Cash Flow':['Working Capital','Margin','Inventory Days','Revenue Growth'],
 'Working Capital':['Inventory Days','Customer Credit','Supplier Terms'],
 ROIC:['Margin','OEE','Working Capital'],
 'Customer Satisfaction':['OTIF','Product Quality','Customer Complaints'],
 'Product Quality':['Quality','First Pass Yield','Supplier Quality','CAPA'],
 'Maintenance Reliability':['Competency','Data','Technology','Continuous Improvement']
 };
 const subdrivers={Availability:['Breakdown','Changeover','Planned Maintenance'],Performance:['Line Speed','Micro Stops','Competency'],Quality:['First Pass Yield','Process Parameters','Supplier Quality'],Forecast:['Demand History','Sales Input','Forecast Accuracy'],'Procurement Cost':['Supplier Qualification','Contract','Purchase Variance'],Yield:['Standard Consumption','Actual Consumption','Process Parameters'],Energy:['Specific Energy','Idle Time'],Price:['Channel','Discount Policy'], 'Labor Productivity':['Competency','Standard Work','Shift Planning'],Inventory:['Inventory Days','Safety Stock'], 'Product Mix':['Product Cost','Market Demand'], 'Safety Stock':['Lead Time','Demand Variability'], 'Batch Size':['Changeover','Shelf Life']};
 const processes = {
 'مدیریت استراتژی':['Strategic Analysis','Objectives','Initiatives','Review'], 'بودجه‌ریزی':['Assumptions','Budget','Approval','Variance Analysis'], 'مدیریت عملکرد':['KPI Design','Data Validation','Review','Action'], 'مدیریت ریسک':['Identify','Assess','Mitigate','Monitor'], 'بازنگری مدیریت':['Inputs','Review','Decisions','Follow-up'], 'توسعه کسب‌وکار':['Opportunity','Business Case','Approval','Launch'],
 'بازار':['Market Insight','Segmentation','Customer Requirements','Sales'], 'برنامه‌ریزی تقاضا':['Demand History','Forecast','Validation','Consensus'], 'برنامه‌ریزی فروش و عملیات':['Demand Review','Supply Review','Reconciliation','Executive S&OP'], 'تدارکات':['Demand','PR','Supplier Selection','PO','Receipt','QC','Inventory','Payment'], 'برنامه‌ریزی تولید':['Demand','Capacity','Material Availability','Schedule','Release'], 'تولید':['Line Preparation','Batch Execution','Process Parameters','Consumption','Yield','Waste','Batch Closure'], 'کیفیت':['Supplier Quality','Incoming QC','Process Control','Finished Product','Traceability','NCR','CAPA'], 'انبار':['Receipt','Quarantine','Release','FEFO','Stock Accuracy','Dispatch'], 'توزیع':['Order','Picking','Routing','Delivery','Proof of Delivery'], 'مشتری':['Order','Service','Complaint','Feedback'],
 'مالی':['Accounting','Cash Flow','Credit','Reporting'], 'منابع انسانی':['Workforce Planning','Recruitment','Competency','Training','Performance'], 'نگهداری و تعمیرات':['Asset Register','Preventive Maintenance','Work Order','Breakdown','Reliability'], 'مهندسی':['Design','Commissioning','Change Control','Technical Documentation'], 'فناوری اطلاعات':['Master Data','Access','Integration','Backup','Support'], 'ایمنی و محیط زیست':['Hazard','Controls','Inspection','Incident','Review'], 'امور اداری':['Facilities','Services','Documents'], 'مدیریت هزینه':['BOM','Standard Consumption','Actual Consumption','Yield','Waste','Standard Cost','Actual Cost','Variance Analysis']
 };
 const processGroups=[['فرآیندهای مدیریتی','Management Processes',Object.keys(processes).slice(0,6)],['فرآیندهای اصلی','Core Processes',Object.keys(processes).slice(6,16)],['فرآیندهای پشتیبان','Support Processes',Object.keys(processes).slice(16)]];
 const defaultOwner={'کیفیت':'مدیر کیفیت','تولید':'مدیر تولید','تدارکات':'مدیر زنجیره تأمین','مدیریت هزینه':'مدیر مالی','برنامه‌ریزی فروش و عملیات':'مدیرعامل','انبار':'مدیر انبار','نگهداری و تعمیرات':'مدیر نگهداری و تعمیرات'};
 const processInfo={
 'کیفیت':{data:'شماره بچ، نتایج آزمون، پارامترهای فرآیند، سوابق مواد و عدم انطباق',kpis:['First Pass Yield','NCR','CAPA Aging','Customer Complaints'],units:['تولید','تدارکات','انبار','فروش'],cap:'ردیابی محصول'},
 'مدیریت هزینه':{data:'BOM، نرخ خرید، مصرف واقعی، ضایعات، ساعات کار و هزینه سربار',kpis:['Margin','Yield','Waste','OEE'],units:['مالی','تولید','تدارکات','انبار'],cap:'مدیریت بهای تمام‌شده'},
 'تدارکات':{data:'PR، PO، زمان تأمین، کیفیت ورودی، قیمت خرید و شرایط پرداخت',kpis:['Supplier Performance','Inventory Days','OTIF'],units:['تولید','کیفیت','انبار','مالی'],cap:'صلاحیت تأمین‌کنندگان'},
 'تولید':{data:'برنامه تولید، شمارش محصول، مصرف مواد، توقف و ضایعات هر بچ',kpis:['OEE','Yield','Waste','Plan Attainment'],units:['کیفیت','نگهداری و تعمیرات','انبار','منابع انسانی'],cap:'برنامه‌ریزی یکپارچه'},
 'انبار':{data:'موجودی بچ، تاریخ انقضا، وضعیت آزادسازی و گردش کالا',kpis:['Inventory Days','OTIF'],units:['کیفیت','تولید','توزیع','مالی'],cap:'ردیابی محصول'},
 'برنامه‌ریزی فروش و عملیات':{data:'پیش‌بینی فروش، ظرفیت، موجودی، محدودیت مواد و سناریوی مالی',kpis:['Forecast Accuracy','OTIF','Inventory Days'],units:['فروش','تولید','مالی','تدارکات'],cap:'برنامه‌ریزی یکپارچه'}
 };
 const perspectives={
 CEO:{kpis:['Revenue Growth','Margin','Cash Flow','Working Capital','OEE','OTIF'],process:['مدیریت استراتژی','برنامه‌ریزی فروش و عملیات','مدیریت عملکرد','بازنگری مدیریت'],links:['مالی','تولید','کیفیت','منابع انسانی','زنجیره تأمین']},
 Finance:{kpis:['Revenue','Margin','Working Capital','Inventory Days','Cost','Budget','Cash Flow'],process:['مدیریت هزینه','بودجه‌ریزی','مالی','تدارکات','تولید','انبار','بازار'],links:['تولید','تدارکات','انبار','فروش']},
 Production:{kpis:['OEE','Yield','Waste','Plan Attainment','Downtime'],process:['تولید','برنامه‌ریزی تولید','تدارکات','کیفیت','نگهداری و تعمیرات','انبار'],links:['کیفیت','نگهداری و تعمیرات','تدارکات','منابع انسانی']},
 Quality:{kpis:['First Pass Yield','NCR','CAPA Aging','Customer Complaints','Waste'],process:['کیفیت','تدارکات','تولید','انبار','مشتری'],links:['تدارکات','تولید','انبار','فروش']},
 HR:{kpis:['Productivity','Turnover','Absenteeism','Training','Labor Productivity'],process:['منابع انسانی','تولید','مدیریت عملکرد','مدیریت استراتژی'],links:['تولید','کیفیت','مالی','مدیرعامل']},
 'Supply Chain':{kpis:['Inventory Days','OTIF','Forecast Accuracy','Supplier Performance'],process:['برنامه‌ریزی تقاضا','برنامه‌ریزی فروش و عملیات','تدارکات','انبار','توزیع','برنامه‌ریزی تولید'],links:['فروش','تولید','کیفیت','مالی']}
 };
 const cockpit=[['مالی','FINANCIAL',[['Revenue','۱۲۰','میلیارد تومان'],['EBITDA','۱۸','میلیارد تومان'],['Cash Flow','۸','میلیارد تومان'],['Working Capital','۳۴','میلیارد تومان']]],['عملیات','OPERATIONS',[['OEE','۶۸','٪'],['Plan Attainment','۹۱','٪'],['Yield','۹۴','٪'],['Waste','۴٫۲','٪'],['Downtime','۳۲','ساعت']]],['زنجیره تأمین','SUPPLY CHAIN',[['Inventory Days','۴۶','روز'],['OTIF','۸۸','٪'],['Forecast Accuracy','۷۶','٪'],['Supplier Performance','۸۲','٪']]],['کیفیت','QUALITY',[['First Pass Yield','۹۶','٪'],['NCR','۱۲','مورد'],['CAPA Aging','۲۱','روز'],['Customer Complaints','۶','مورد']]],['نیروی انسانی','PEOPLE',[['Productivity','۳۸','کیلوگرم / نفرساعت'],['Turnover','۲٫۱','٪'],['Absenteeism','۱٫۸','٪'],['Training','۶','ساعت / نفر']]]];
 const definitions={
 OEE:['دسترس‌پذیری × عملکرد × کیفیت','ثبت توقف، شمارش تولید، سرعت استاندارد و محصول سالم','مدیر تولید'],Margin:['(فروش خالص − بهای تمام‌شده فروش) ÷ فروش خالص × ۱۰۰','فروش خالص، بهای تمام‌شده و تخصیص هزینه','مدیر مالی'],OTIF:['سفارش‌های کامل و به‌موقع ÷ کل سفارش‌های سررسیدشده × ۱۰۰','تاریخ تعهد، تاریخ تحویل، مقدار سفارش و مقدار تحویل','مدیر زنجیره تأمین'],'Inventory Days':['متوسط ارزش موجودی ÷ بهای تمام‌شده دوره × روزهای دوره','ارزش موجودی و بهای تمام‌شده همان دوره','مدیر زنجیره تأمین با مدیر مالی'],Waste:['مقدار ضایعات ÷ مقدار مواد ورودی × ۱۰۰','وزن ورودی و ضایعات به تفکیک بچ؛ مرز محاسبه باید توافق شود','مدیر تولید'],Yield:['خروجی قابل قبول ÷ ورودی مواد × ۱۰۰','وزن ورودی و خروجی قابل قبول هر بچ','مدیر تولید'],'First Pass Yield':['محصول پذیرفته‌شده بدون اصلاح ÷ کل محصول ارزیابی‌شده × ۱۰۰','نتایج آزمون و سوابق دوباره‌کاری','مدیر کیفیت'], 'Forecast Accuracy':['۱ − مجموع خطای مطلق ÷ مجموع فروش واقعی؛ تعریف WAPE','پیش‌بینی نسخه ثابت و فروش واقعی در سطح محصول / دوره','مدیر برنامه‌ریزی'], 'Supplier Performance':['امتیاز ترکیبی کیفیت، زمان تحویل و پاسخ‌گویی؛ وزن‌ها نیازمند توافق‌اند','سوابق PO، دریافت، QC و ارزیابی تأمین‌کننده','مدیر تدارکات']};
 const rhythms=[
 {id:'daily',fa:'روزانه',en:'DAILY',title:'جلسه تولید',participants:'تولید، کیفیت، نگهداری و تعمیرات، برنامه‌ریزی و انبار',kpis:['OEE','Waste','Plan Attainment','Downtime','NCR'],decisions:'رفع محدودیت شیفت، آزادسازی محصول، تخصیص منابع و اولویت تعمیر',owner:'مدیر تولید',deadline:'تا پایان شیفت / روز',follow:'مرور اقدامات باز در جلسه روز بعد'},
 {id:'weekly',fa:'هفتگی',en:'WEEKLY',title:'مرور عملیات',participants:'تولید، کیفیت، زنجیره تأمین، فروش و منابع انسانی',kpis:['OTIF','Inventory Days','Forecast Accuracy','Yield','CAPA Aging'],decisions:'هماهنگی برنامه تولید، مواد، توزیع و اقدام اصلاحی بین‌واحدی',owner:'مدیر عملیات',deadline:'تا مرور هفتگی بعد',follow:'ثبت وضعیت اقدام و علت تأخیر'},
 {id:'monthly',fa:'ماهانه',en:'MONTHLY',title:'مرور کسب‌وکار',participants:'مدیرعامل، مالی، تولید، کیفیت، منابع انسانی و زنجیره تأمین',kpis:['Revenue','EBITDA','Cash Flow','Working Capital','Margin'],decisions:'اصلاح بودجه و سناریوی نقدینگی، ترکیب محصول و تخصیص منابع',owner:'مدیرعامل',deadline:'مطابق موعد مصوب هر اقدام',follow:'کنترل اجرای تصمیمات در مرور ماه بعد'},
 {id:'quarterly',fa:'فصلی',en:'QUARTERLY',title:'بازنگری استراتژی',participants:'مدیرعامل و تیم مدیریت؛ سهام‌داران در صورت نیاز',kpis:['Revenue Growth','ROIC','Market Growth','New Products'],decisions:'بازنگری اولویت‌های استراتژیک، سرمایه‌گذاری و نقشه راه قابلیت‌ها',owner:'مدیرعامل',deadline:'مطابق برنامه ابتکارات مصوب',follow:'مرور پیشرفت ابتکارات و فرضیات استراتژی'}
 ];
 const problems=[
 {title:'بهای تمام‌شده بالا است',concern:'حفظ سودآوری و نقدینگی',kpi:'Margin',cost:'بهای تمام‌شده محصول',drivers:['BOM','Procurement Cost','Actual Consumption','Yield','Waste','OEE'],process:['مدیریت هزینه','تدارکات','تولید','انبار'],owners:'مالی + تولید + تدارکات',data:'BOM معتبر، نرخ خرید، مصرف هر بچ، ضایعات، توقف و هزینه سربار',metrics:['Margin','Yield','Waste','OEE'],action:'توافق بر مرز محاسبه هزینه، تحلیل انحراف مصرف و انتخاب یک محصول برای بررسی مشترک'},
 {title:'تحویل به مشتری دیر انجام می‌شود',concern:'حفظ مشتری و اعتبار تعهد تحویل',kpi:'OTIF',cost:'قابلیت تحویل سفارش',drivers:['Forecast','S&OP','Production Planning','Material Availability','Production','Warehouse','Distribution'],process:['برنامه‌ریزی تقاضا','برنامه‌ریزی فروش و عملیات','برنامه‌ریزی تولید','تدارکات','انبار','توزیع'],owners:'فروش + برنامه‌ریزی + زنجیره تأمین + تولید',data:'تاریخ تعهد و تحویل، سفارش، پیش‌بینی، موجودی آزاد و محدودیت مواد',metrics:['OTIF','Forecast Accuracy','Inventory Days','Plan Attainment'],action:'انتخاب چند سفارش دیررس و بازسازی مسیر از تعهد فروش تا تحویل'},
 {title:'کیفیت محصول ناپایدار است',concern:'اعتماد مشتری و ایمنی محصول',kpi:'Product Quality',cost:'پایداری کیفیت در هر بچ',drivers:['Supplier','Incoming QC','Process Parameters','Production','QC','Traceability','NCR','CAPA'],process:['تدارکات','کیفیت','تولید','انبار'],owners:'کیفیت + تولید + تدارکات',data:'بچ مواد و محصول، نتایج آزمون، پارامترهای فرآیند و سوابق عدم انطباق',metrics:['First Pass Yield','NCR','CAPA Aging','Customer Complaints'],action:'انتخاب یک عدم انطباق و ردیابی آن تا ماده، پارامتر فرآیند و اثربخشی CAPA'},
 {title:'ضایعات بیش از انتظار است',concern:'حفظ مواد، ظرفیت و حاشیه سود',kpi:'Waste',cost:'اتلاف مواد در جریان تولید',drivers:['Supplier Quality','Standard Consumption','Actual Consumption','Process Parameters','Yield','OEE'],process:['تولید','کیفیت','مدیریت هزینه','نگهداری و تعمیرات'],owners:'تولید + کیفیت + مالی + نگهداری و تعمیرات',data:'وزن ورودی، خروجی سالم، ضایعات و دوباره‌کاری به تفکیک محصول / شیفت / بچ',metrics:['Waste','Yield','OEE','First Pass Yield'],action:'توافق بر تعریف ضایعات، تفکیک علل ثبت‌شده و بررسی یک بچ با اتلاف بالا'}
 ];
 const roadmap=[
 ['هم‌راستایی استراتژیک','Strategic Alignment','توافق بر جهت و اولویت‌های کارخانه','مصاحبه مدیریت؛ فرضیات رشد؛ اولویت‌بندی اهداف','جهت استراتژیک؛ اولویت‌ها؛ فرضیات کلیدی','مدیرعامل و تیم مدیریت','تصویر آینده و دغدغه‌های ذی‌نفعان'],
 ['مدل عملیاتی هدف','Target Operating Model','تعریف چگونگی خلق ارزش و اداره کارخانه','مدل خدمت؛ مرز تصمیم‌ها؛ کانال‌ها؛ قابلیت‌های موردنیاز','مدل عملیاتی هدف؛ نقشه قابلیت‌ها','مدیرعامل، مالی، عملیات و فروش','هم‌راستایی استراتژیک'],
 ['معماری فرآیندی','Process Architecture','تعریف جریان‌های انتها به انتها','نقشه سطح یک و دو؛ ارتباطات؛ فرآیندهای حیاتی','معماری فرآیندی و فهرست فرآیندهای حیاتی','مدیران واحدها و صاحبان فرآیند','مدل عملیاتی و قابلیت‌ها'],
 ['طراحی فرآیندهای حیاتی','Critical Process Design','تبدیل فرآیندهای حیاتی به جریان اجرایی','ورودی و خروجی؛ کنترل‌ها؛ نقاط تحویل؛ استثناها','نقشه فرآیند؛ نقاط کنترل؛ نیازمندی داده','صاحبان فرآیند و کاربران اجرایی','معماری و اولویت فرآیندها'],
 ['سازمان و مسئولیت','Organization & RACI','شفاف‌سازی اختیار و پاسخ‌گویی','مالکیت فرآیند؛ نقش‌ها؛ ماتریس RACI؛ شایستگی','ساختار نقش‌ها؛ RACI؛ شرح مسئولیت','مدیرعامل، منابع انسانی و مدیران','فرآیندهای حیاتی طراحی‌شده'],
 ['شاخص و مدیریت عملکرد','KPI & Performance Management','اتصال هدف، داده و تصمیم','تعریف شاخص؛ فرمول؛ مالک؛ تناوب؛ کنترل کیفیت داده','شناسنامه KPI؛ الگوی مرور عملکرد','مالی، صاحبان فرآیند و فناوری اطلاعات','اهداف، فرآیندها، مالکیت و منابع داده'],
 ['خط‌مشی و مستندسازی','Policies / SOP / ISO','مستندسازی نظام اجرایی و الزامات مرتبط','خط‌مشی؛ SOP؛ فرم‌ها؛ ارزیابی شکاف الزامات','اسناد کنترل‌شده؛ طرح انطباق','کیفیت و صاحبان فرآیند','فرآیند و مسئولیت و کنترل‌های روشن'],
 ['دیجیتال‌سازی','ERP / BI / Digitalization','پشتیبانی سیستم‌ها از مدل مدیریت','داده پایه؛ نیازمندی ERP؛ یکپارچگی؛ گزارش‌ها','مدل داده؛ نیازمندی سیستم؛ نمونه داشبورد','فناوری اطلاعات، مالی و کاربران کلیدی','فرآیند، KPI و مالکیت داده'],
 ['استقرار و راهبری','Implementation & Governance','تبدیل طراحی به رفتار پایدار مدیریت','اجرای آزمایشی؛ آموزش؛ جلسات؛ پیگیری اقدام؛ بهبود','برنامه استقرار؛ نظام جلسات؛ فهرست اقدامات','مدیرعامل، صاحبان فرآیند و تیم اجرا','خروجی مراحل مرتبط و آمادگی سازمان']
 ];
 const categories=['اولویت استراتژیک','مسئله','دغدغه مدیریتی','فرآیند حیاتی','قابلیت موردنیاز','ریسک','شاخص','تصمیم','سؤال باز'];
 const tags=['استراتژی','مالی','تولید','کیفیت','منابع انسانی','زنجیره تأمین','فناوری اطلاعات','ریسک'];
 const seed=[['اولویت استراتژیک','تثبیت تولید و کیفیت پیش از توسعه ظرفیت','استراتژی','High'],['مسئله','مصرف واقعی مواد با استاندارد مقایسه نمی‌شود','تولید','High'],['قابلیت موردنیاز','ردیابی محصول از ماده اولیه تا مشتری','کیفیت','High'],['ریسک','عدم شفافیت موجودی آزاد و تاریخ انقضا','زنجیره تأمین','High'],['سؤال باز','برای رشد سه‌ساله کدام کانال فروش اولویت دارد؟','استراتژی','Medium']];
 return {pages,chain,axes,prompts,capabilities,layers,labels,drivers,subdrivers,processes,processGroups,defaultOwner,processInfo,perspectives,cockpit,definitions,rhythms,problems,roadmap,categories,tags,seed};
})();
