/* All parsing and reporting run locally in the browser. No row data is persisted. */
const $ = id => document.getElementById(id);
const months = ['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const fields = ['ردیف','نام بیمارستان','نام بخش گزارش دهنده','بخش 2','شیفت وقوع خطا','نوع گزارش خطا','تاریخ وقوع خطا','نوع خطا','علت وقوع خطا','سن بیمار','عنوان خطا','نوع خطا2','سمت','تاریخ ثبت فرم'];
const protectedFields = new Set(['نام و نام خانوادگی تکمیل کننده','شماره پرونده','شرح خطا','نام گزارش دهنده']);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = { rows:[], trendRows:[], headers:[], charts:[], filename:'', period:'', errors:0, outside:0, ai:null };
function clean(v){ return String(v ?? '').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ').trim(); }
function dateParts(v){ const m=clean(v).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).match(/(1[34]\d{2})\D*(0?[1-9]|1[0-2])\D*(\d{1,2})/); return m&&Number(m[3])>=1&&Number(m[3])<=31?{year:m[1],month:Number(m[2]),day:Number(m[3])}:null; }
function count(rows,field){ const m=new Map(); rows.forEach(r=>{const k=clean(r[field])||'ثبت نشده';m.set(k,(m.get(k)||0)+1)});return [...m].sort((a,b)=>b[1]-a[1]); }
function topCounts(rows,field,n=10,other='سایر موارد'){const a=count(rows,field);return a.length>n?[...a.slice(0,n),[other,a.slice(n).reduce((s,x)=>s+x[1],0)]]:a}
function titleForPeriod(rows){let dates=rows.map(r=>dateParts(r['تاریخ وقوع خطا'])).filter(Boolean);let years=[...new Set(dates.map(d=>d.year))].sort();let ms=[...new Set(dates.map(d=>d.month))].sort((a,b)=>a-b);return `${years.join('، ')||'نامشخص'} · ${ms.map(m=>months[m-1]).join('، ')||'ماه نامشخص'}`;}
async function parseWorkbook(buffer){const z=await JSZip.loadAsync(buffer);const wb=z.file('xl/workbook.xml');if(!wb)throw Error('فایل، قالب معتبر Excel نیست.');
 const xml=s=>new DOMParser().parseFromString(s,'application/xml');const shared=z.file('xl/sharedStrings.xml')?xml(await z.file('xl/sharedStrings.xml').async('string')):null;
 const strings=shared?[...shared.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent).join('')):[];
 const sheet=z.file('xl/worksheets/sheet1.xml');if(!sheet)throw Error('برگهٔ داده در فایل پیدا نشد.');const doc=xml(await sheet.async('string'));if(doc.querySelector('parsererror'))throw Error('ساختار برگهٔ اکسل قابل خواندن نیست.');
 const matrix=[...doc.getElementsByTagName('row')].map(row=>{let cells=[];[...row.getElementsByTagName('c')].forEach(c=>{let ref=c.getAttribute('r')||'';let letters=ref.match(/^[A-Z]+/);if(!letters)return;let idx=[...letters[0]].reduce((a,v)=>a*26+v.charCodeAt(0)-64,0)-1;let v=c.getElementsByTagName('v')[0]?.textContent??'';if(c.getAttribute('t')==='s')v=strings[Number(v)]??'';if(c.getAttribute('t')==='inlineStr')v=[...c.getElementsByTagName('t')].map(x=>x.textContent).join('');cells[idx]=v;});return cells;});
 const headIdx=matrix.findIndex(r=>r.some(v=>clean(v)==='ردیف')&&r.some(v=>clean(v)==='تاریخ وقوع خطا'));if(headIdx<0)throw Error('ستون‌های ردیف و تاریخ وقوع خطا پیدا نشدند. قالب فایل را بررسی کنید.');
 const headers=matrix[headIdx].map(clean);const required=['نام بخش گزارش دهنده','بخش 2','شیفت وقوع خطا','نوع گزارش خطا','تاریخ وقوع خطا','نوع خطا','سن بیمار','عنوان خطا','نوع خطا2','سمت'];let missing=required.filter(h=>!headers.includes(h));if(missing.length)throw Error('ستون‌های مورد نیاز یافت نشد: '+missing.join('، '));
 let rows=[],invalid=0;matrix.slice(headIdx+1).forEach(values=>{if(!values.some(v=>clean(v)))return;const r={};headers.forEach((h,i)=>{if(h)r[h]=values[i]??''});if(!dateParts(r['تاریخ وقوع خطا']))invalid++;rows.push(r)});if(!rows.length)throw Error('هیچ رکوردی پیدا نشد.');return {headers,rows,invalid};}
function ageBand(v){let s=clean(v);if(!s||s==='-'||s==='.')return 8;if(/^\d+\s*ماهه?$/.test(s))return 0;let n=Number(s);return !Number.isFinite(n)||n<0||n>120?8:n<=18?0:n<=30?1:n<=40?2:n<=50?3:n<=60?4:n<=70?5:n<=80?6:7}
function chartDefinitions(rows,trendRows){let keyed=new Map();trendRows.forEach(r=>{let d=dateParts(r['تاریخ وقوع خطا']);let key=`${d.year}/${String(d.month).padStart(2,'0')}`;keyed.set(key,(keyed.get(key)||0)+1)});let trend=[...keyed].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,n])=>[`${months[Number(k.slice(-2))-1]} ${k.slice(0,4)}`,n]);
 const shift=count(rows,'شیفت وقوع خطا'), occurrence=topCounts(rows,'بخش 2',10,'سایر بخش‌های مرتبط'), reporting=count(rows,'نام بخش گزارش دهنده'), types=count(rows,'نوع خطا'), reportType=count(rows,'نوع گزارش خطا'), errors=topCounts(rows,'نوع خطا2',9,'سایر انواع خطا'), roles=count(rows,'سمت'), causes=count(rows,'علت وقوع خطا');const mainTypes=count(rows,'عنوان خطا');const medicine=rows.filter(r=>clean(r['عنوان خطا'])==='خطای دارویی');const medicineShift=count(medicine,'شیفت وقوع خطا');const missing=[['سن نامعتبر یا ثبت نشده',rows.filter(r=>ageBand(r['سن بیمار'])===8).length],['نوع گزارش ثبت نشده',rows.filter(r=>!clean(r['نوع گزارش خطا'])).length],['نوع جزئی خطا ثبت نشده',rows.filter(r=>!clean(r['نوع خطا2'])).length],['تاریخ وقوع نامعتبر',rows.filter(r=>!dateParts(r['تاریخ وقوع خطا'])).length]];
 const ageBins=['۰–۱۸','۱۹–۳۰','۳۱–۴۰','۴۱–۵۰','۵۱–۶۰','۶۱–۷۰','۷۱–۸۰','بالای ۸۰','نامشخص'];let ages=ageBins.map(x=>[x,0]);rows.forEach(r=>ages[ageBand(r['سن بیمار'])][1]++);
 const reportModes=['خود اظهاری','گزارش خطای سایرین','ثبت نشده',...reportType.map(([name])=>name).filter(name=>!['خود اظهاری','گزارش خطای سایرین','ثبت نشده'].includes(name))].filter(name=>reportType.some(([actual])=>actual===name));const reportBreakdown=reporting.map(([unit])=>reportModes.map(mode=>rows.filter(r=>(clean(r['نام بخش گزارش دهنده'])||'ثبت نشده')===unit&&(clean(r['نوع گزارش خطا'])||'ثبت نشده')===mode).length));const fullShifts=shift.map(([name])=>name),topReporters=count(rows,'نام بخش گزارش دهنده').slice(0,5).map(([name])=>name);
 const periodKeys=[...keyed.keys()].sort(),monthLabels=periodKeys.map(k=>`${months[Number(k.slice(-2))-1]} ${k.slice(0,4)}`);
 const monthOf=r=>{const d=dateParts(r['تاریخ وقوع خطا']);return d?`${d.year}/${String(d.month).padStart(2,'0')}`:null};
 const periodShifts=count(trendRows,'شیفت وقوع خطا').map(d=>d[0]);
 const monthlyShift=periodKeys.map((key,i)=>[monthLabels[i],...periodShifts.map(shift=>trendRows.filter(r=>monthOf(r)===key&&(clean(r['شیفت وقوع خطا'])||'ثبت نشده')===shift).length)]);
 const periodSections=count(trendRows,'بخش 2'),primarySections=periodSections.slice(0,5).map(d=>d[0]);
 const sectionGroups=[...primarySections,...(periodSections.length>5?['سایر بخش‌های مرتبط']:[])];
 const monthlySection=sectionGroups.map(section=>[section,...periodKeys.map(key=>trendRows.filter(r=>monthOf(r)===key&&(section==='سایر بخش‌های مرتبط'?!primarySections.includes(clean(r['بخش 2'])||'ثبت نشده'):(clean(r['بخش 2'])||'ثبت نشده')===section)).length)]);
 const periodModes=count(trendRows,'نوع گزارش خطا').map(d=>d[0]);
 const monthlyReport=periodKeys.map((key,i)=>[monthLabels[i],...periodModes.map(mode=>trendRows.filter(r=>monthOf(r)===key&&(clean(r['نوع گزارش خطا'])||'ثبت نشده')===mode).length)]);
 const defs=[
 ['shift','فراوانی خطا به تفکیک شیفت','توزیع تعداد ثبت‌ها در شیفت‌های کاری',shift,'bar'],
 ['trend','روند خطاهای ثبت شده',`تاریخ معتبر در دورهٔ ${dateParts(trendRows[0]?.['تاریخ وقوع خطا'])?.year||'گزارش'} · ${trendRows.length} رکورد از ${rows.length}`,trend,'line'],
 ['occurrence','فراوانی به تفکیک بخش مرتبط','ستون «بخش 2»؛ محل قطعی وقوع از نام این ستون قابل اثبات نیست',occurrence,'bar'],
 ['reporting','بخش‌های گزارش دهنده خطا','همه واحدها؛ تفکیک خود اظهاری، گزارش خطای سایرین و ثبت نشده',reporting,'bar'],
 ['cross','بخش گزارش دهنده × شیفت','پنج واحد نخست با همه شیفت‌ها؛ مخرج: همان پنج واحد',topReporters.map(name=>[name,...fullShifts.map(s=>rows.filter(r=>clean(r['نام بخش گزارش دهنده'])===name&&(clean(r['شیفت وقوع خطا'])||'ثبت نشده')===s).length)]),'cross'],
 ['monthlyShift','فراوانی گزارش خطا: شیفت × ماه',`فقط ${trendRows.length} گزارش با تاریخ معتبر دوره؛ همه شیفت‌ها`,monthlyShift,'cross'],
 ['monthlySection','فراوانی گزارش خطا: بخش مرتبط × ماه',`فقط ${trendRows.length} گزارش با تاریخ معتبر دوره؛ ستون «بخش 2» و گروه سایر بخش‌ها`,monthlySection,'cross'],
 ['monthlyReport','شیوه ثبت گزارش خطا × ماه',`فقط ${trendRows.length} گزارش با تاریخ معتبر دوره؛ تفکیک خوداظهاری و سایرین`,monthlyReport,'cross'],
 ['reportType','شیوه ثبت گزارش خطا','خود اظهاری، گزارش خطای سایرین و ثبت نشده؛ از ستون «نوع گزارش خطا»',reportType,'donut'],
 ['severity','توزیع نوع خطا','نزدیک به خطا، بدون آسیب و همراه با آسیب',types,'donut'],
 ['errorKind','انواع خطاهای ثبت شده','طبقه‌بندی «نوع خطا2»',errors,'bar'],
 ['causes','علت وقوع خطا','فراوانی علت‌های ثبت شده',causes,'bar'],
 ['roles','گزارش دهندگان بر اساس سمت','فراوانی نقش‌های شغلی',roles,'donut'],
 ['age','توزیع سنی بیماران','سن‌های خالی یا غیرعددی در «نامشخص» شمرده می‌شوند',ages,'bar'],
 ['mainType','دسته‌های اصلی خطا','توزیع بر اساس ستون «عنوان خطا»',mainTypes,'donut'],
 ['medicineShift','خطاهای دارویی در شیفت‌ها','فقط رکوردهای با عنوان «خطای دارویی»',medicineShift,'bar'],
 ['missing','موارد نیازمند تکمیل داده','دسته‌ها ممکن است روی یک رکورد هم‌پوشانی داشته باشند',missing,'bar'] ];
 return defs.map(([id,title,subtitle,data,type])=>({id,title,subtitle,data,type,selected:true,note:'',series:id==='cross'?fullShifts:id==='monthlyShift'?periodShifts:id==='monthlySection'?monthLabels:id==='monthlyReport'?periodModes:id==='reporting'?reportModes:null,breakdown:id==='reporting'?reportBreakdown:null}));}
function analysisFor(c){
 const total=c.type==='cross'?c.data.reduce((s,d)=>s+d.slice(1).reduce((a,b)=>a+b,0),0):c.data.reduce((s,d)=>s+(Number(d[1])||0),0);
 const ranked=c.type==='cross'?c.data.map(d=>[d[0],d.slice(1).reduce((a,b)=>a+b,0)]).sort((a,b)=>b[1]-a[1]):[...c.data].sort((a,b)=>b[1]-a[1]);
 const lead=ranked[0]||['بدون داده',0];
 const observation=c.id==='missing'?`${lead[0]} در ${lead[1]} رکورد دیده می‌شود. تعداد نقص‌ها ممکن است به یک رکورد مشترک مربوط باشد.`:`در «${c.title}»، بیشترین تعداد ثبت مربوط به «${lead[0]}» با ${lead[1]} مورد از ${total} مورد است.`;
 const cases={
 shift:['آیا تعداد بیماران و حجم کار در شیفت‌ها یکسان بوده است؟','آمار مراجعه و تعداد کارکنان هر شیفت را کنار تعداد گزارش‌ها بررسی کنید.'],
 trend:['آیا تغییر تعداد گزارش‌ها با تغییر مراجعه یا شیوه ثبت هم‌زمان بوده است؟','روند ماهانه را با تعداد پذیرش و تغییرات فرایند گزارش‌دهی مقایسه کنید.'],
 occurrence:['آیا بخش‌های پرتکرار بیماران یا فعالیت بیشتری داشته‌اند؟','برای مقایسه بخش‌ها، تعداد گزارش را نسبت به تعداد بیمار یا روز بستری محاسبه کنید.'],
 reporting:['آیا فراوانی گزارش نشانه فعالیت بیشتر در ثبت است یا تفاوت مواجهه؟','با مسئولان بخش‌ها کیفیت و کامل بودن گزارش‌دهی را مرور کنید.'],
 cross:['آیا الگو پس از درنظر گرفتن حجم کار هر بخش و شیفت باقی می‌ماند؟','جدول مشترک بخش و شیفت را همراه آمار فعالیت همان زمان مرور کنید.'],
 monthlyShift:['آیا حجم فعالیت و تعداد کارکنان هر شیفت در ماه‌ها تغییر کرده است؟','تعداد گزارش هر شیفت را کنار مراجعه و میزان نیروی همان شیفت در هر ماه بررسی کنید.'],
 monthlySection:['آیا ثبت ماهانه با حجم بیمار یا تغییر فرایند هر بخش مرتبط است؟','برای پنج بخش پرتکرار و سایر بخش‌ها مخرج مراجعه یا روز بستری ماهانه گردآوری کنید.'],
 monthlyReport:['آیا تغییر نسبت خوداظهاری به گزارش سایرین با سیاست ثبت یا بازخورد هم‌زمان بوده است؟','ماه‌به‌ماه مسیر محرمانه ثبت و زمان بازخورد به گزارش‌دهندگان را بررسی کنید.'],
 reportType:['چه عواملی بر میزان خوداظهاری و گزارش سایرین اثر می‌گذارند؟','مسیر محرمانه و بازخورد گزارش‌دهی را با کارکنان بررسی کنید.'],
 severity:['طبقه‌بندی شدت رویدادها در همه بخش‌ها به یک روش انجام شده است؟','چند پرونده از هر دسته را برای یکسان‌سازی تعریف‌ها بازبینی کنید.'],
 errorKind:['کدام زیرفرایندها در دسته پرتکرار سهم بیشتری دارند؟','چند گزارش پرتکرار را برای یافتن نقطه قابل اصلاح در فرایند بررسی کنید.'],
 causes:['آیا علت‌ها پس از بررسی پرونده ثبت شده‌اند یا برداشت اولیه گزارش‌دهنده‌اند؟','نمونه‌ای از گزارش‌ها را با روش بررسی ریشه‌ای و بدون سرزنش مرور کنید.'],
 roles:['آیا سهم گزارش‌دهندگان با تعداد کارکنان هر حرفه تناسب دارد؟','فرصت و سهولت ثبت گزارش برای گروه‌های شغلی را بررسی کنید.'],
 age:['چه سهمی از سن‌ها خالی یا غیرعددی است و آمار پذیرش هر سن چقدر است؟','ابتدا کیفیت ثبت سن را بهبود دهید؛ سپس نرخ متناسب با جمعیت هر گروه را بسنجید.'],
 mainType:['کدام دسته‌ها نیازمند بررسی جزئی‌تر هستند؟','برای دسته‌های پرتکرار، نوع جزئی خطا و فرایند مرتبط را بازبینی کنید.'],
 medicineShift:['آیا حجم تجویز و تحویل دارو در شیفت‌ها مشابه بوده است؟','تعداد خطاهای دارویی را کنار تعداد تجویز یا دوزهای تجویزشده هر شیفت ببینید.'],
 missing:['کدام فیلد برای تحلیل ایمنی ضروری است و چرا ناقص مانده است؟','فیلدهای ضروری را در فرم مشخص و به تکمیل‌کننده بازخورد بدهید.']
 };
 return {observation,question:cases[c.id][0],action:cases[c.id][1],caveat:'این‌ها تعداد گزارش‌های ثبت شده‌اند؛ بدون مخرج مواجهه، از آن‌ها نرخ خطر یا علت قطعی نتیجه نمی‌شود.'};
}
function svgChart(chart){const data=chart.data;if(chart.id==='reporting'){const max=Math.max(1,...data.map(d=>Number(d[1])||0)),colors=['#119987','#4b8cda','#e5a858','#a684d8'];return `<div class="unit-chart" role="img" aria-label="${escapeHtml(chart.title)}"><div class="unit-legend">${chart.series.map((name,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${escapeHtml(name)}</span>`).join('')}</div>${data.map(([unit,total],i)=>{let offset=0;return `<div class="unit-row"><span class="unit-label">${escapeHtml(unit)}</span><span class="unit-bar">${chart.breakdown[i].map((value,j)=>{const width=value/max*100;return `<span title="${escapeHtml(chart.series[j])}: ${value}" style="width:${width}%;background:${colors[j%colors.length]}"></span>`}).join('')}</span><strong>${total}</strong></div>`}).join('')}</div>`}if(chart.id==='errorKind'){const max=Math.max(1,...data.map(d=>Number(d[1])||0));return `<div class="error-rows" role="img" aria-label="${escapeHtml(chart.title)}">${data.map(([label,value])=>`<div class="error-row"><span class="error-label">${escapeHtml(label)}</span><span class="error-bar-track"><span class="error-bar-fill" style="width:${Math.max(2,Number(value)/max*100)}%"></span></span><strong>${Number(value)||0}</strong></div>`).join('')}</div>`} let max=Math.max(1,...data.map(d=>Math.max(...d.slice(1).map(Number))));let colors=['#119987','#4b8cda','#e5a858','#a684d8','#ec7773'];if(chart.type==='donut'){let sum=data.reduce((v,d)=>v+d[1],0)||1,cx=155,cy=118,r=75,start=0;let arcs=data.map(([k,v],i)=>{let len=v/sum*2*Math.PI,from=start;start+=len;let x1=cx+r*Math.cos(from),y1=cy+r*Math.sin(from),x2=cx+r*Math.cos(start),y2=cy+r*Math.sin(start),large=len>Math.PI?1:0;return len>=6.283?`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="27"/>`:`<path d="M ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="27"/>`}).join('');let legend=data.map(([k,v],i)=>`<circle cx="350" cy="${43+i*34}" r="6" fill="${colors[i%colors.length]}"/><text x="367" y="${47+i*34}" text-anchor="start" direction="rtl" style="font-size:11px;font-weight:800">${escapeHtml(k)} · ${v}</text>`).join('');return `<svg viewBox="0 0 640 250">${arcs}<circle cx="155" cy="118" r="52" fill="white"/><text x="155" y="114" text-anchor="middle" style="font-size:20px;font-weight:bold">${sum}</text><text x="155" y="134" text-anchor="middle">ثبت</text>${legend}</svg>`}
 if(chart.type==='cross'){let rowH=36,maxTotal=Math.max(1,...data.map(d=>d.slice(1).reduce((a,b)=>a+b,0))),legendY=32+data.length*rowH;let items=data.map((d,i)=>{let y=25+i*rowH,x=210;let segments=d.slice(1).map((v,j)=>{let width=(Number(v)||0)/maxTotal*360,segment=`<rect x="${x}" y="${y-14}" width="${width}" height="20" fill="${colors[j%colors.length]}"/><text x="${x+width/2}" y="${y+1}" text-anchor="middle" fill="#173342" style="font-weight:800">${width>22?v:''}</text>`;x+=width;return segment}).join('');return `<text x="12" y="${y}" text-anchor="start" style="font-weight:800"><title>${escapeHtml(d[0])}</title>${escapeHtml(d[0].slice(0,24))}</text>${segments}<text x="${Math.min(x+7,587)}" y="${y}" style="font-weight:800">${d.slice(1).reduce((a,b)=>a+(Number(b)||0),0)}</text>`}).join('');let legend=(chart.series||[]).map((v,i)=>`<rect x="${20+i%3*200}" y="${legendY+Math.floor(i/3)*23}" width="11" height="11" fill="${colors[i%colors.length]}"/><text x="${35+i%3*200}" y="${legendY+10+Math.floor(i/3)*23}" style="font-size:11px;font-weight:800">${escapeHtml(v)}</text>`).join('');return `<svg viewBox="0 0 640 ${legendY+Math.ceil((chart.series||[]).length/3)*23+7}">${items}${legend}</svg>`}
 if(chart.type==='line'){let coords=data.map((d,i)=>[40+i*(560/Math.max(data.length-1,1)),205-d[1]/max*165]);let line=coords.map(([x,y])=>`${x},${y}`).join(' ');return `<svg viewBox="0 0 640 250"><line x1="30" y1="205" x2="620" y2="205" stroke="#dce8ea"/><polyline points="${line}" fill="none" stroke="#119987" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="5" fill="#119987"/><text x="${x}" y="${y-12}" text-anchor="middle">${data[i][1]}</text><text x="${x}" y="228" text-anchor="middle">${escapeHtml(data[i][0].slice(0,16))}</text>`).join('')}</svg>`}
 let n=data.length,rowH=Math.min(36,210/Math.max(n,1));return `<svg viewBox="0 0 640 ${chart.id==='errorKind'?285:245}">${data.map(([k,v],i)=>{let y=12+i*rowH,w=v/max*280;return `<text x="12" y="${y+rowH*.68}" text-anchor="start" style="font-weight:800"><title>${escapeHtml(k)}</title>${escapeHtml(String(k).slice(0,26))}</text><rect x="290" y="${y+3}" width="${w}" height="${Math.max(8,rowH-8)}" rx="5" fill="${colors[i%colors.length]}"/><text x="${296+w}" y="${y+rowH*.68}">${v}</text>`}).join('')}${chart.id==='errorKind'?`<text x="320" y="265" text-anchor="middle" style="font-size:11px;font-weight:800">برچسب داده: تعداد گزارش برای هر نوع خطا</text>`:''}</svg>`;}
function render(){let rows=state.rows;let topShift=count(rows,'شیفت وقوع خطا')[0], peak=state.charts.find(c=>c.id==='trend').data.slice().sort((a,b)=>b[1]-a[1])[0];$('period').textContent='دوره: '+state.period;
 $('kpis').innerHTML=[['◈',rows.length,'کل خطاهای ثبت شده'],['◷',peak?peak[1]:'—',`بیشترین ثبت ماهانه · ${peak?.[0]||'—'}`],['☀',topShift?.[1]??'—',`شیفت پرتکرار · ${topShift?.[0]||'—'}`],['✚',new Set(rows.map(r=>clean(r['بخش 2'])).filter(Boolean)).size,'بخش دارای ثبت خطا']].map(([icon,n,label])=>`<div class="kpi"><div class="icon">${icon}</div><strong>${n}</strong><small>${escapeHtml(label)}</small></div>`).join('');
 $('chartGrid').innerHTML=state.charts.map((c,i)=>{const a=analysisFor(c);return `<article class="card"><div class="card-top"><div><span class="eyebrow">نمودار ${String(i+1).padStart(2,'0')}</span><h3><span class="chart-icon">${window.chartIcon(c.id)}</span>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.subtitle)}</p></div><label class="pick"><input type="checkbox" data-chart="${c.id}" ${c.selected?'checked':''}> انتخاب</label></div><div class="chart${c.id==='errorKind'?' error-list':c.id==='reporting'?' unit-list':''}">${svgChart(c)}</div><div class="analysis-panel"><div class="analysis-heading">تحلیل آمادهٔ بررسی</div><p><b>آنچه داده نشان می‌دهد</b>${escapeHtml(a.observation)}</p><p><b>پرسش برای بررسی</b>${escapeHtml(a.question)}</p><p><b>گام پیشنهادی</b>${escapeHtml(a.action)}</p><label class="note-label" for="note-${c.id}">جمع‌بندی یا تصمیم نهایی شما <span>اختیاری</span></label><textarea id="note-${c.id}" data-note="${c.id}" placeholder="پس از بررسی پرونده‌ها، تصمیم، مسئول و زمان پیگیری را بنویسید.">${escapeHtml(c.note)}</textarea></div></article>`}).join('');
 $('monthFilter').innerHTML='<option value="">همه ماه‌ها</option>'+[...new Set(state.rows.map(r=>dateParts(r['تاریخ وقوع خطا'])).filter(Boolean).map(d=>`${d.year}/${String(d.month).padStart(2,'0')}`))].sort().map(s=>`<option value="${s}">${months[Number(s.slice(-2))-1]} ${s.slice(0,4)}</option>`).join('');$('tableHead').innerHTML='<tr>'+fields.filter(f=>state.headers.includes(f)&&!protectedFields.has(f)).map(f=>`<th>${escapeHtml(f)}</th>`).join('')+'</tr>';renderTable();selected();}
function renderTable(){let search=clean($('search').value).toLowerCase(),month=$('monthFilter').value;let data=state.rows.filter(r=>(!month||clean(r['تاریخ وقوع خطا']).startsWith(month))&&(!search||fields.some(f=>!protectedFields.has(f)&&clean(r[f]).toLowerCase().includes(search))));$('tableBody').innerHTML=data.slice(0,500).map(r=>`<tr${dateParts(r['تاریخ وقوع خطا'])?'':' class="invalid-date"'}>`+fields.filter(f=>state.headers.includes(f)&&!protectedFields.has(f)).map(f=>`<td title="${escapeHtml(r[f])}">${escapeHtml(r[f])}</td>`).join('')+'</tr>').join('');$('tableCount').textContent=`${data.length} رکورد${data.length>500?' · ۵۰۰ ردیف نخست نمایش داده شده‌اند':''}`;}
function selected(){let n=state.charts.filter(c=>c.selected).length;$('selectedCount').textContent=`${n} نمودار انتخاب شده`;$('exportBtn').disabled=!n}
async function makePpt(){ return window.makeSafetyPresentation(state,analysisFor); }
$('file').addEventListener('change',async e=>{let f=e.target.files?.[0];if(!f)return;$('fileName').textContent=f.name;$('notice').className='notice';$('notice').textContent='در حال خواندن فایل اکسل…';await new Promise(requestAnimationFrame);try{if(typeof JSZip==='undefined')throw Error('ابزار خواندن اکسل بارگذاری نشده است. فایل standalone.html را باز کنید یا کل پوشهٔ پروژه را یکجا نگه دارید.');let result=await parseWorkbook(await f.arrayBuffer());state.rows=result.rows;state.ai=null;state.headers=result.headers;state.errors=result.invalid;state.filename=f.name;const valid=result.rows.map(r=>dateParts(r['تاریخ وقوع خطا'])).filter(Boolean),years=new Map();valid.forEach(d=>years.set(d.year,(years.get(d.year)||0)+1));const dominantYear=[...years].sort((a,b)=>b[1]-a[1])[0]?.[0];state.trendRows=result.rows.filter(r=>dateParts(r['تاریخ وقوع خطا'])?.year===dominantYear);state.outside=valid.length-state.trendRows.length;state.period=titleForPeriod(state.trendRows);state.charts=chartDefinitions(state.rows,state.trendRows);$('fileName').textContent=f.name;$('notice').className='notice';$('notice').textContent=`${result.rows.length} رکورد از «${f.name}» خوانده شد و همه در جدول و نمودارهای دسته‌ای شمرده می‌شوند. نمودار روند: ${state.trendRows.length} تاریخ در دورهٔ ${dominantYear}.${result.invalid?` ${result.invalid} تاریخ نامعتبر/خالی با رنگ مشخص در جدول باقی است.`:''}${state.outside?` ${state.outside} تاریخ از سال دیگر فقط از روند این سال کنار گذاشته شد.`:''} داده‌ها فقط در این مرورگر پردازش می‌شوند.`;render();window.dispatchEvent(new Event('safety-data-loaded'))}catch(err){$('notice').className='notice error';$('notice').textContent='خطا در خواندن اکسل: '+(err?.message||String(err));console.error('Excel import failed',err)}});
$('search').addEventListener('input',()=>state.rows.length&&renderTable());$('monthFilter').addEventListener('change',()=>state.rows.length&&renderTable());$('chartGrid').addEventListener('change',e=>{let id=e.target.dataset.chart;if(id){state.charts.find(c=>c.id===id).selected=e.target.checked;selected()}});$('chartGrid').addEventListener('input',e=>{let id=e.target.dataset.note;if(id)state.charts.find(c=>c.id===id).note=e.target.value});$('exportBtn').addEventListener('click',async()=>{let b=$('exportBtn');b.disabled=true;b.textContent='در حال ساخت…';try{await makePpt();b.textContent='دریافت پاورپوینت ←'}catch(e){$('notice').className='notice error';$('notice').textContent=e.message;b.textContent='تلاش دوباره'}finally{selected()}});

window.addEventListener('error',e=>{if(!state.rows.length){$('notice').className='notice error';$('notice').textContent='اجرای برنامه متوقف شد: '+(e.message||'یکی از فایل‌های برنامه بارگذاری نشده است. از standalone.html استفاده کنید.')}});
